services:
  db:
    image: postgres:16-alpine
    container_name: bfx_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bfx
    ports:
      - "5432"
    volumes:
      - bfx_pg:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bfx_app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/bfx?schema=public
      SESSION_SECRET: change-me
    depends_on:
      - db
    command: sh -c "npx prisma generate && yarn dev"

volumes:
  bfx_pg:
    name: bfx_pg_data
