apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bfx-ingress
  namespace: bfx
spec:
  ingressClassName: traefik
  rules:
    - host: bfx.softlive.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bfx-app
                port:
                  number: 80
