apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfx

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - postgres.yaml
  - app.yaml
  - ingress.yaml

images:
  - name: 730335375436.dkr.ecr.sa-east-1.amazonaws.com/bfx/bfx-shop
    newName: 730335375436.dkr.ecr.sa-east-1.amazonaws.com/bfx/bfx-shop
