apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bfx

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secrets.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - app.yaml
  - ingress.yaml
