apiVersion: v1
kind: Service
metadata:
  name: bfx-shop-service
  namespace: bfx
spec:
  selector:
    app: bfx-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
